import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToastProvider from "@/components/ToastProvider";

const OutfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${OutfitFont.className} h-full antialiased`}>
      <body suppressHydrationWarning>
        <Navbar />
        <main className="max-w-[90%] mx-auto">
          {children}
        </main>
        <Footer />

        
        <ToastProvider />
      </body>
    </html>
  );
}